name: Synchronize two Shaarli instances

on:
  workflow_dispatch:

jobs:
  synchronize-shaarlis:
    name: 🧪 Synchronize two Shaarli instances
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v3

      - name: ⎔ Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: 🚀 Synchronize Shaarli
        run: NODE_TLS_REJECT_UNAUTHORIZED=0 bun synchronize.ts
        env:
          SHAARLI_SOURCE_URL: "https://links.aschen.tech/api/v1"
          SHAARLI_SOURCE_SECRET: ${{ secrets.SHAARLI_ASCHEN_KEY }}
          SHAARLI_TARGET_URL: "https://news.gen-ai.fr/api/v1"
          SHAARLI_TARGET_SECRET: ${{ secrets.SHAARLI_GENAI_KEY }}
          TAGS: "c-ai"
